# Generated by Django 4.1.1 on 2022-09-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_infocounter_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocounter',
            name='projects',
            field=models.CharField(default='21', max_length=50),
        ),
        migrations.AddField(
            model_name='infocounter',
            name='support',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='infocounter',
            name='workers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='infocounter',
            name='clients',
            field=models.IntegerField(null=True),
        ),
    ]
