# Generated by Django 4.1.1 on 2022-09-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_infocounter_projects_infocounter_support_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headDiscription', models.CharField(max_length=100)),
                ('webdev', models.CharField(max_length=100)),
                ('Mlearning', models.CharField(max_length=100)),
                ('dataA', models.CharField(max_length=100)),
            ],
        ),
    ]
