# Generated by Django 4.1.1 on 2022-09-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_servicedes_appdev_servicedes_automation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceDes',
            new_name='ServiceDescription',
        ),
    ]
