# Generated by Django 4.1.1 on 2022-09-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('facebook', models.URLField()),
                ('github', models.URLField()),
                ('twitter', models.URLField()),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
