# Generated by Django 4.1.1 on 2022-09-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_contact_delete_contactinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='github',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='twitter',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default='none', max_length=5000),
        ),
    ]
