# Generated by Django 4.1.1 on 2022-09-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_contact_address_remove_contact_facebook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Phone',
            new_name='subject',
        ),
    ]
