# Generated by Django 4.1.1 on 2022-09-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('short_desc', models.TextField(max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_pictures/')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('twitter', models.CharField(default='#', max_length=200)),
                ('facebook', models.CharField(default='#', max_length=200)),
                ('instagram', models.CharField(default='#', max_length=200)),
                ('linkedin', models.CharField(default='#', max_length=200)),
            ],
        ),
    ]
