# Generated by Django 4.1.1 on 2022-09-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='servicedescription',
            name='DigitalMarketing',
            field=models.TextField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicedescription',
            name='Mlearning',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicedescription',
            name='appdev',
            field=models.TextField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicedescription',
            name='automation',
            field=models.TextField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicedescription',
            name='dataA',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicedescription',
            name='headDiscription',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicedescription',
            name='webdev',
            field=models.TextField(max_length=100),
        ),
    ]
