# Generated by Django 4.1.1 on 2022-09-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_servicedescription_digitalmarketing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='website/team_pictures/'),
        ),
    ]
