# Generated by Django 4.1.1 on 2022-09-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_team_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infocounter',
            name='projects',
        ),
        migrations.AddField(
            model_name='infocounter',
            name='counter',
            field=models.CharField(default='counter', max_length=50),
        ),
        migrations.AddField(
            model_name='infocounter',
            name='project',
            field=models.IntegerField(null=True),
        ),
    ]
