# Generated by Django 4.1.1 on 2022-09-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_infocounter_projects_infocounter_counter_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infocounter',
            new_name='Info_counter',
        ),
    ]
