# Generated by Django 4.1.1 on 2022-09-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_rename_infocounter_info_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='services', max_length=50)),
                ('heading', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=500)),
            ],
        ),
    ]
