# Generated by Django 4.1.1 on 2022-10-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_rename_infocounter_info_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedescription',
            name='description',
            field=models.TextField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='servicedescription',
            name='heading',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicedescription',
            name='logo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
