# Generated by Django 4.1.2 on 2022-10-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testclient_pic', models.ImageField(default='', upload_to='website/client_test/images')),
                ('testclient_name', models.CharField(max_length=50)),
                ('testclient_profession', models.CharField(max_length=50)),
                ('testclient_desc', models.CharField(max_length=500)),
            ],
        ),
    ]
