# Generated by Django 4.1.1 on 2022-10-05 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_servicedescription_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedescription',
            name='DigitalMarketing',
        ),
        migrations.RemoveField(
            model_name='servicedescription',
            name='Mlearning',
        ),
        migrations.RemoveField(
            model_name='servicedescription',
            name='appdev',
        ),
        migrations.RemoveField(
            model_name='servicedescription',
            name='automation',
        ),
        migrations.RemoveField(
            model_name='servicedescription',
            name='dataA',
        ),
        migrations.RemoveField(
            model_name='servicedescription',
            name='headDiscription',
        ),
        migrations.RemoveField(
            model_name='servicedescription',
            name='webdev',
        ),
    ]
