# Generated by Django 4.1.2 on 2022-10-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='testclient_pic',
        ),
    ]
