# Generated by Django 4.1.2 on 2022-10-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_remove_servicedescription_digitalmarketing_and_more'),
        ('website', '0021_remove_testimonial_testclient_pic'),
    ]

    operations = [
    ]
