# Generated by Django 4.1.2 on 2022-10-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_merge_20221005_1201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
