# Generated by Django 4.1.2 on 2022-10-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_desc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
