# Generated by Django 4.1.2 on 2022-10-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_blog_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='website/blog_banners/'),
        ),
    ]
