# Generated by Django 4.1.2 on 2022-10-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_pic',
            field=models.ImageField(blank=True, null=True, upload_to='blog/author_pic/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='blog/blog_banners/'),
        ),
    ]
