# Generated by Django 4.1.2 on 2022-10-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_blog_content_remove_comment_comment_blog_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_pic',
            field=models.ImageField(blank=True, default='https://t3.ftcdn.net/jpg/03/46/83/96/360_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg', null=True, upload_to='blog/user_pic/'),
        ),
    ]
