# Generated by Django 4.1.2 on 2022-10-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_pic',
            field=models.ImageField(blank=True, null=True, upload_to='blog/user_pic/'),
        ),
    ]
