# Generated by Django 4.1.2 on 2022-10-08 20:12

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_comment_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='blog/default_pic.png', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[40, 40], upload_to='blog/user_pic/'),
        ),
    ]
