# Generated by Django 4.1.2 on 2022-10-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_comment_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(help_text='Comment', max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_email',
            field=models.EmailField(blank=True, help_text='E-mail', max_length=300),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(help_text='Name', max_length=250),
        ),
    ]
