# Generated by Django 4.1.2 on 2022-10-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_comment_body_alter_comment_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_prof',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_desc',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
