# Generated by Django 4.1.2 on 2022-10-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_author_facebook_alter_author_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='linkedin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='stack_overflow',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='facebook',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='instagram',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
